Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly DatabaseService _db;
        public CategoryController(DatabaseService db)
        {
            _db = db;
        }
    
        public async Task<IActionResult> Index()
        {
            List<TransactionCategory> transactionCategories = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionCategories = await _db.GetTransactionCategories(userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("CategoryIndex", transactionCategories);
        }
        
        public IActionResult Add()
        {
            return View("NewCategory");
        }
        public async Task<IActionResult> Edit(Guid categoryID)
        {
            TransactionCategory transactionCategory = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionCategory = await _db.GetTransactionCategory(categoryID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("EditCategory", transactionCategory);
        }

        public async Task<IActionResult> AddNewCategory(TransactionCategory newCategory)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newCategory.UserID = userID;
                await _db.InsertTransactionCategory(newCategory);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditExistingCategory(TransactionCategory newCategory)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newCategory.UserID = userID;
                await _db.UpdateTransactionCategory(newCategory);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteCategory(Guid categoryID)
        {
            try
            {
                await _db.DeleteTransactionCategory(categoryID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/RoadmapController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class RoadmapController : Controller
    {
        public IActionResult Index()
        {
            return View("ViewRoadmap");
        }
    }
}

Controllers/SourcesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class SourcesController : Controller
    {
        private readonly DatabaseService _db;
        public SourcesController(DatabaseService db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<TransactionSource> transactionSources = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionSources = await _db.GetTransactionSources(userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("ViewTransactionSources", transactionSources);
        }
        public IActionResult Add()
        {
            return View("NewSource");
        }
        public async Task<IActionResult> Edit(Guid sourceID)
        {
            TransactionSource transactionSource = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionSource = await _db.GetTransactionSource(sourceID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("EditSource", transactionSource);
        }

        public async Task<IActionResult> AddNewSource(TransactionSource newSource)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newSource.UserId = userID;
                await _db.InsertTransactionSource(newSource);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditExistingSource(TransactionSource newSource)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newSource.UserId = userID;
                await _db.UpdateTransactionSource(newSource);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteSource(Guid sourceID)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                await _db.DeleteTransactionSource(sourceID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }
    }
}

Views/Shared/_Layout.cshtml
@using TropicalBudget.Utilities
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tropical Budget</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
    <script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.3/dist/Chart.min.js"></script>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/TropicalBudget.styles.css" asp-append-version="true" />
    <link rel="icon" href="~/images/logo_transparent.png" type="image/png">

</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                    <img style="width:50px;" src="~/images/logo_transparent.png" />
                    <span>Tropical Budget</span>
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Categories</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Sources" asp-action="Index">Sources</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Roadmap" asp-action="Index">Roadmap</a>
                        </li>
                    </ul>
                    <div class="d-flex gap-2 align-items-center">
                        @if (User.Identity?.IsAuthenticated ?? false)
                        {
                            <a asp-area="" asp-controller="Account" asp-action="Profile">
                                <img class="rounded-circle" style="width:30px" src="@UserUtility.GetUserProfilePhoto(User)" />
                            </a>
                            <a asp-area="" asp-controller="Account" asp-action="Logout">Logout</a>
                                        }
                                        else
                                        {
                            <a asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                        }
                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        @* <div class="container"> *@
        @*     &copy; 2025 - Tropical Budget - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a> *@
        @* </div> *@
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>