Models/TransactionType.cs
namespace TropicalBudget.Models
{
    public class TransactionType
    {
        public Guid ID { get; set; }
        public string Name { get; set; }
    }
}

Controllers/CategoryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class CategoryController : Controller
    {
        private readonly DatabaseService _db;
        public CategoryController(DatabaseService db)
        {
            _db = db;
        }
    
        public async Task<IActionResult> Index()
        {
            List<TransactionCategory> transactionCategories = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionCategories = await _db.GetTransactionCategories(userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("CategoryIndex", transactionCategories);
        }
        
        public IActionResult Add()
        {
            return View("NewCategory");
        }
        public async Task<IActionResult> Edit(Guid categoryID)
        {
            TransactionCategory transactionCategory = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionCategory = await _db.GetTransactionCategory(categoryID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("EditCategory", transactionCategory);
        }

        public async Task<IActionResult> AddNewCategory(TransactionCategory newCategory)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newCategory.UserID = userID;
                await _db.InsertTransactionCategory(newCategory);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditExistingCategory(TransactionCategory newCategory)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newCategory.UserID = userID;
                await _db.UpdateTransactionCategory(newCategory);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteCategory(Guid categoryID)
        {
            try
            {
                await _db.DeleteTransactionCategory(categoryID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/InsightsController.cs
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    public class InsightsController : Controller
    {
        private readonly DatabaseService _db;
        public InsightsController(DatabaseService db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index(Guid budgetID, int? year, int? month)
        {
            if (budgetID == Guid.Empty)
                return RedirectToAction("Index", "Home");
            Tuple<Guid, List<Transaction>> budgetTransactions = new(new(), new());
            try
            {
                string userID = UserUtility.GetUserID(User);
                DateTime currentDate = DateTime.Now;
                string currentMonth = string.Empty;
                DateTime startDate;
                DateTime endDate;
                if (year == null || month == null)
                {
                    currentMonth = $"{currentDate.ToString("MMMM")}, {currentDate.ToString("yyyy")}";
                    //get start and end date of the month
                    startDate = new DateTime(currentDate.Year, currentDate.Month, 1, 0, 0, 0);
                    endDate = startDate.AddMonths(1).AddSeconds(-1);
                }
                else
                {
                    if (month.Value > 12 || month.Value < 1)
                    {
                        return RedirectToAction("Index");
                    }
                    startDate = new DateTime(year.Value, month.Value, 1, 0, 0, 0);
                    endDate = startDate.AddMonths(1).AddSeconds(-1);
                    currentMonth = $"{startDate.ToString("MMMM")}, {startDate.ToString("yyyy")}";
                }
                TempData["currentMonthString"] = currentMonth;
                TempData["startDate"] = startDate;
                Budget budget = await _db.GetBudget(userID, budgetID);
                TempData["BudgetName"] = budget != null && !string.IsNullOrWhiteSpace(budget.Name) ? budget.Name : "Unknown";
                List<Transaction> transactions = await _db.GetTransactions(budgetID, startDate, endDate);
                budgetTransactions = new(budgetID, transactions);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("ViewInsights", budgetTransactions);
        }
    }
}

Controllers/SourcesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class SourcesController : Controller
    {
        private readonly DatabaseService _db;
        public SourcesController(DatabaseService db)
        {
            _db = db;
        }
        public async Task<IActionResult> Index()
        {
            List<TransactionSource> transactionSources = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionSources = await _db.GetTransactionSources(userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("ViewTransactionSources", transactionSources);
        }
        public IActionResult Add()
        {
            return View("NewSource");
        }
        public async Task<IActionResult> Edit(Guid sourceID)
        {
            TransactionSource transactionSource = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                transactionSource = await _db.GetTransactionSource(sourceID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View("EditSource", transactionSource);
        }

        public async Task<IActionResult> AddNewSource(TransactionSource newSource)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newSource.UserId = userID;
                await _db.InsertTransactionSource(newSource);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> EditExistingSource(TransactionSource newSource)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                newSource.UserId = userID;
                await _db.UpdateTransactionSource(newSource);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteSource(Guid sourceID)
        {
            try
            {
                string userID = UserUtility.GetUserID(User);
                await _db.DeleteTransactionSource(sourceID, userID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/TransactionController.cs
using System.Globalization;
using CsvHelper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using TropicalBudget.Models;
using TropicalBudget.Services;
using TropicalBudget.Utilities;

namespace TropicalBudget.Controllers
{
    [Authorize]
    public class TransactionController : Controller
    {
        private readonly DatabaseService _db;
        public TransactionController(DatabaseService db)
        {
            _db = db;
        }

        public async Task<IActionResult> Index(Guid budgetID, int? year, int? month)
        {
            if (budgetID == Guid.Empty)
                return RedirectToAction("Index", "Home");
            Tuple<Guid, List<Transaction>> budgetTransactions = new(new(), new());
            try
            {
                string userID = UserUtility.GetUserID(User);
                DateTime currentDate = DateTime.Now;
                string currentMonth = string.Empty;
                DateTime startDate;
                DateTime endDate;
                if (year == null || month == null)
                {
                    currentMonth = $"{currentDate.ToString("MMMM")}, {currentDate.ToString("yyyy")}";
                    //get start and end date of the month
                    startDate = new DateTime(currentDate.Year, currentDate.Month, 1, 0, 0, 0);
                    endDate = startDate.AddMonths(1).AddSeconds(-1);
                }
                else
                {
                    if (month.Value > 12 || month.Value < 1)
                    {
                        return RedirectToAction("Index");
                    }
                    startDate = new DateTime(year.Value, month.Value, 1, 0, 0, 0);
                    endDate = startDate.AddMonths(1).AddSeconds(-1);
                    currentMonth = $"{startDate.ToString("MMMM")}, {startDate.ToString("yyyy")}";
                }
                TempData["currentMonthString"] = currentMonth;
                TempData["startDate"] = startDate;
                Budget budget = await _db.GetBudget(userID, budgetID);
                TempData["BudgetName"] = budget != null && !string.IsNullOrWhiteSpace(budget.Name) ? budget.Name : "Unknown";
                List<Transaction> transactions = await _db.GetTransactions(budgetID, startDate, endDate);
                budgetTransactions = new(budgetID, transactions);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            
            return View("ViewTransactions", budgetTransactions);
        }

        public async Task<IActionResult> New(Guid budgetID)
        {
            Transaction newTransaction = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                List<TransactionCategory> transactionCategories = await _db.GetTransactionCategories(userID);
                List<TransactionSource> transactionSources = await _db.GetTransactionSources(userID);
                List<TransactionType> transactionTypes = await _db.GetTransactionTypes();
                TempData["TransactionCategories"] = transactionCategories;
                TempData["TransactionSources"] = transactionSources;
                TempData["TransactionTypes"] = transactionTypes;
                newTransaction.BudgetID = budgetID;
                newTransaction.TransactionDate = DateTime.Now;
                if (transactionTypes.Any(type => type.Name.Equals(TransactionUtility.TRANSACTION_TYPE_EXPENSE)))
                {
                    newTransaction.TransactionTypeID = transactionTypes.FirstOrDefault(type => type.Name.Equals(TransactionUtility.TRANSACTION_TYPE_EXPENSE)).ID;
                }
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            
            return View("NewTransaction",newTransaction);
        }

        public async Task<IActionResult> EditTransaction(Guid transactionID)
        {
            Transaction editingTransaction = new();
            try
            {
                string userID = UserUtility.GetUserID(User);
                List<TransactionCategory> transactionCategories = await _db.GetTransactionCategories(userID);
                List<TransactionSource> transactionSources = await _db.GetTransactionSources(userID);
                List<TransactionType> transactionTypes = await _db.GetTransactionTypes();
                TempData["TransactionCategories"] = transactionCategories;
                TempData["TransactionSources"] = transactionSources;
                TempData["TransactionTypes"] = transactionTypes;
                editingTransaction = await _db.GetTransaction(transactionID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return View(editingTransaction);
        }


        public async Task<IActionResult> AddNewTransaction(Transaction newTransaction)
        {
            try
            {
                await _db.InsertTransaction(newTransaction);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index",new {budgetID = newTransaction.BudgetID});
        }
        public async Task<IActionResult> EditExistingTransaction(Transaction newTransaction)
        {
            try
            {
                await _db.UpdateTransaction(newTransaction);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index", new { budgetID = newTransaction.BudgetID });
        }

        public async Task<IActionResult> DeleteTransaction(Guid budgetID, Guid transactionID)
        {
            try
            {
                await _db.DeleteTransaction(transactionID);
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return RedirectToAction("Index", new { budgetID });
        }

        public async Task<IActionResult> Export(Guid budgetID, int? year, int? month)
        {
            MemoryStream stream = new();
            string filePath = $"Transactions.csv";
            try
            {
                DateTime startDate = new DateTime(year.Value, month.Value, 1, 0, 0, 0);
                DateTime endDate = startDate.AddMonths(1).AddSeconds(-1);
                filePath = $"Transactions - {startDate.ToString("MMM, yyyy")}.csv";
                List<Transaction> transactions = await _db.GetTransactions(budgetID, startDate, endDate);
                transactions = transactions.OrderByDescending(x => x.CreatedAt).ToList();
                List<TransactionExport> transactionExports = await TransactionUtility.ConvertTransactionsToExportTransactions(transactions);
                using (StreamWriter writer = new(stream, leaveOpen:true))
                {
                    CsvWriter csv = new(writer, new CultureInfo("en-US"));
                    csv.WriteRecords(transactionExports);
                }
                stream.Position = 0;
            }
            catch (Exception ex)
            {
                SentrySdk.CaptureException(ex);
            }
            return File(stream, "application/octet-stream", filePath);
        }
    }
}

Views/Transaction/EditTransaction.cshtml
@model Transaction
@{
    ViewData["Title"] = "Edit Transaction";
    List<TransactionCategory> transactionCategories = (List<TransactionCategory>)TempData["TransactionCategories"];
    List<TransactionSource> transactionSources = (List<TransactionSource>)TempData["TransactionSources"];
    List<TransactionType> transactionTypes = (List<TransactionType>)TempData["TransactionTypes"];
}

<div class="text-center">
    <h1 class="display-4">Edit Transaction</h1>
    <div>
        @using (Html.BeginForm("EditExistingTransaction", "Transaction"))
        {
            @Html.AntiForgeryToken();
            <div class="d-flex flex-column gap-2">
                @Html.HiddenFor(x => x.ID)
                @Html.HiddenFor(x => x.BudgetID)
                @Html.LabelFor(x =>x.Amount)
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    @Html.TextBoxFor(x => x.Amount, new { @placeholder = "Amount", @type = "number", @min = 0, @class = "form-control", @step = "0.01", @required = true })
                </div>
                @if (transactionCategories == null || transactionCategories.Count <= 0)
                {
                            <div class="alert alert-danger" role="alert">
                                No categories available. Please <a asp-controller="Category" asp-action="Index">add a category</a> first.
                            </div>
                }
                @Html.LabelFor(x =>x.CategoryID, "Category")
                @Html.DropDownListFor(x => x.CategoryID, new SelectList(transactionCategories, "ID","Name"), new {@class = "form-select", @required = true})
                @if (transactionSources == null || transactionSources.Count <= 0)
                {
                            <div class="alert alert-danger" role="alert">
                                No sources available. Please <a asp-controller="Sources" asp-action="Index">add a source</a> first.
                            </div>
                }
                @Html.LabelFor(x =>x.SourceID, "From")
                @Html.DropDownListFor(x => x.SourceID, new SelectList(transactionSources, "ID", "Name"), new { @class = "form-select", @required = true })
                @Html.LabelFor(x => x.TransactionTypeID, "Transaction Type")
                @Html.DropDownListFor(x => x.TransactionTypeID, new SelectList(transactionTypes, "ID", "Name"), new { @class = "form-select", @required = true })
                @Html.LabelFor(x => x.TransactionDate, "Date")
                @Html.TextBoxFor(x => x.TransactionDate, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control", @required = true })
                @Html.LabelFor(x => x.Note)
                @Html.TextBoxFor(x => x.Note, new { @placeholder = "Note", @type = "text", @class = "form-control" })

                <input type="submit" name="SaveButton" class="btn btn-primary" value="Save" />
                <input type="button" name="ExitButton" onclick="navigateToHome()" class="btn btn-outline-primary" value="Exit" />

            </div>
        }
    </div>
</div>

<script>
    const navigateToHome = () =>{
        location.href = "@Url.Action("Index", "Transaction")" +"?budgetID=@(Model.BudgetID.ToString())";
    }
</script>

Views/Transaction/NewTransaction.cshtml
@using TropicalBudget.Utilities
@model Transaction
@{
    ViewData["Title"] = "New Transaction";
    List<TransactionCategory> transactionCategories = (List<TransactionCategory>)TempData["TransactionCategories"];
    List<TransactionSource> transactionSources = (List<TransactionSource>)TempData["TransactionSources"];
    List<TransactionType> transactionTypes = (List<TransactionType>)TempData["TransactionTypes"];
}

<div class="text-center">
    <h1 class="display-4">New Transaction</h1>
    <div>
        @using (Html.BeginForm("AddNewTransaction", "Transaction"))
        {
            @Html.AntiForgeryToken();
            <div class="d-flex flex-column gap-2">
                @Html.HiddenFor(x => x.BudgetID)
                @Html.LabelFor(x =>x.Amount)
                <div class="input-group mb-3">
                    <div class="input-group-prepend">
                        <span class="input-group-text">$</span>
                    </div>
                    @Html.TextBoxFor(x => x.Amount, new { @placeholder = "Amount", @type = "number", @min = 0, @class = "form-control", @step = "0.01", @required = true })
                </div>
				@if (transactionCategories == null || transactionCategories.Count <= 0)
				{
                    <div class="alert alert-danger" role="alert">
                        No categories available. Please <a asp-controller="Category" asp-action="Index">add a category</a> first.
                    </div>
				}
                @Html.LabelFor(x =>x.CategoryID, "Category")
                @Html.DropDownListFor(x => x.CategoryID, new SelectList(transactionCategories, "ID", "Name"), new { @class = "form-select", @required = true })
                @if (transactionSources == null || transactionSources.Count <= 0)
                {
                    <div class="alert alert-danger" role="alert">
                        No sources available. Please <a asp-controller="Sources" asp-action="Index">add a source</a> first.
                    </div>
                }
                @Html.LabelFor(x =>x.SourceID, "From", new{ @id ="source-label"})
                @Html.DropDownListFor(x => x.SourceID, new SelectList(transactionSources, "ID", "Name"), new { @class = "form-select", @required = true })
                @Html.LabelFor(x => x.TransactionTypeID, "Transaction Type")
                @Html.DropDownListFor(x => x.TransactionTypeID, new SelectList(transactionTypes, "ID", "Name"), new { @class = "form-select", @onchange = "onTransactionTypeChanged(this.options[this.selectedIndex].text)", @required = true })
                @Html.LabelFor(x => x.TransactionDate, "Date")
                @Html.TextBoxFor(x => x.TransactionDate, "{0:yyyy-MM-dd}", new { @type = "date", @class = "form-control", @required = true })
                @Html.LabelFor(x => x.Note)
                @Html.TextBoxFor(x => x.Note, new { @placeholder = "Note", @type = "text", @class = "form-control" })

                <input type="submit" name="SaveButton" class="btn btn-primary" value="Save" />
                <input type="button" name="ExitButton" onclick="navigateToHome()" class="btn btn-outline-primary" value="Exit" />

            </div>
        }
    </div>
</div>

<script>
    const navigateToHome = () =>{
        location.href = "@Url.Action("Index", "Transaction")" +"?budgetID=@(Model.BudgetID.ToString())";
    }
    const onTransactionTypeChanged = (transactionType) =>  {
        const source_label = document.getElementById('source-label');
        if(transactionType == "@TransactionUtility.TRANSACTION_TYPE_EXPENSE"){
            source_label.innerText = "From";
        }else if(transactionType == "@TransactionUtility.TRANSACTION_TYPE_INCOME"){
            source_label.innerText = "To";

        }
    }
</script>

Views/Transaction/_TransactionCard.cshtml
@model Transaction
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Transaction transaction = Model;
}

<div class="d-flex gap-2 justify-content-between align-items-center bg-light rounded px-4 py-2">
    <div class="d-flex flex-wrap align-items-center gap-2">
        <span class="rounded-circle" style="width:20px; height:20px; background-color: @transaction.CategoryColor; display:block"></span>

        <div class="d-flex flex-column gap-0">
            @if(!string.IsNullOrWhiteSpace(transaction.Note)){
                <span class="fs-4 fw-normal">@(transaction.Note)</span>
                <span class="fs-6 fw-light">@(transaction.CategoryName)</span>
            }
            else{
                <span class="fs-4 fw-normal">@(transaction.CategoryName)</span>
            }
        </div>
    </div>
    <div class="d-flex gap-2 align-items-center flex-wrap justify-content-end">
        @if(transaction.TransactionType.Equals("Income")){
            <span style="color:green" class="fw-bold fs-5">+@($"{transaction.Amount:c}")</span>
        }else{
            <span class="fw-bold fs-5">@($"{transaction.Amount:c}")</span>
        }
        <div class="d-flex gap-2 align-items-center flex-wrap">
            <i style="cursor:pointer" onclick="editTransaction('@(transaction.ID)')" class="bi bi-pencil-fill text-white px-3 py-2 fs-4 bg-primary rounded"></i>
            <i style="cursor:pointer" onclick="deleteTransaction('@(transaction.ID)')" class="bi bi-trash text-white px-3 py-2 fs-4 bg-danger rounded"></i>
        </div>
    </div>
               
</div>